import '../riscv/isa.dart';
import '../util/pretty_string.dart';

/// OpenSBI platform description.
///
/// Generates the platform-specific C header and source files that
/// OpenSBI needs to initialize and run on a Harbor SoC.
///
/// ```dart
/// final platform = OpenSbiPlatform(
///   name: 'creek',
///   isa: creekV1Isa,
///   clintBase: 0x02000000,
///   plicBase: 0x0C000000,
///   uartBase: 0x10000000,
///   memBase: 0x80000000,
///   memSize: 0x80000000,
/// );
///
/// File('platform.c').writeAsStringSync(platform.generatePlatformSource());
/// File('platform.h').writeAsStringSync(platform.generatePlatformHeader());
/// ```
class OpenSbiPlatform with HarborPrettyString {
  /// Platform name.
  final String name;

  /// ISA configuration.
  final RiscVIsaConfig isa;

  /// Number of harts.
  final int hartCount;

  /// CLINT base address.
  final int clintBase;

  /// PLIC base address.
  final int plicBase;

  /// Number of PLIC interrupt sources.
  final int plicSources;

  /// UART base address (for console).
  final int uartBase;

  /// UART clock frequency.
  final int uartClock;

  /// UART baud rate.
  final int uartBaud;

  /// Main memory base address.
  final int memBase;

  /// Main memory size in bytes.
  final int memSize;

  /// Reset vector address.
  final int resetVector;

  const OpenSbiPlatform({
    required this.name,
    required this.isa,
    this.hartCount = 1,
    required this.clintBase,
    required this.plicBase,
    this.plicSources = 32,
    required this.uartBase,
    this.uartClock = 0,
    this.uartBaud = 115200,
    required this.memBase,
    required this.memSize,
    this.resetVector = 0x80000000,
  });

  /// Generates the OpenSBI platform C header.
  String generatePlatformHeader() {
    final guard = 'HARBOR_${name.toUpperCase()}_PLATFORM_H';
    return '''
/* Auto-generated by Harbor for platform: $name */
#ifndef $guard
#define $guard

#define HARBOR_HART_COUNT        $hartCount
#define HARBOR_CLINT_BASE        0x${clintBase.toRadixString(16)}UL
#define HARBOR_PLIC_BASE         0x${plicBase.toRadixString(16)}UL
#define HARBOR_PLIC_NUM_SOURCES  $plicSources
#define HARBOR_UART_BASE         0x${uartBase.toRadixString(16)}UL
#define HARBOR_UART_CLOCK        $uartClock
#define HARBOR_UART_BAUD         $uartBaud
#define HARBOR_MEM_BASE          0x${memBase.toRadixString(16)}UL
#define HARBOR_MEM_SIZE          0x${memSize.toRadixString(16)}UL
#define HARBOR_RESET_VECTOR      0x${resetVector.toRadixString(16)}UL

#endif /* $guard */
''';
  }

  /// Generates the OpenSBI platform C source.
  String generatePlatformSource() {
    return '''
/* Auto-generated by Harbor for platform: $name */
#include <sbi/sbi_platform.h>
#include <sbi/sbi_console.h>
#include <sbi_utils/irqchip/plic.h>
#include <sbi_utils/serial/uart8250.h>
#include <sbi_utils/timer/aclint_mtimer.h>
#include <sbi_utils/ipi/aclint_mswi.h>

#define HARBOR_CLINT_BASE        0x${clintBase.toRadixString(16)}UL
#define HARBOR_PLIC_BASE         0x${plicBase.toRadixString(16)}UL
#define HARBOR_PLIC_NUM_SOURCES  $plicSources
#define HARBOR_UART_BASE         0x${uartBase.toRadixString(16)}UL
#define HARBOR_UART_CLOCK        $uartClock
#define HARBOR_UART_BAUD         $uartBaud

static struct plic_data plic = {
    .addr = HARBOR_PLIC_BASE,
    .num_src = HARBOR_PLIC_NUM_SOURCES,
};

static struct aclint_mswi_data mswi = {
    .addr = HARBOR_CLINT_BASE,
    .size = 0x4000,
    .first_hartid = 0,
    .hart_count = $hartCount,
};

static struct aclint_mtimer_data mtimer = {
    .mtime_freq = 10000000,
    .mtime_addr = HARBOR_CLINT_BASE + 0xBFF8,
    .mtime_size = 8,
    .mtimecmp_addr = HARBOR_CLINT_BASE + 0x4000,
    .mtimecmp_size = 8,
    .first_hartid = 0,
    .hart_count = $hartCount,
    .has_64bit_mmio = true,
};

static int ${name}_early_init(bool cold_boot)
{
    return 0;
}

static int ${name}_final_init(bool cold_boot)
{
    return 0;
}

static int ${name}_console_init(void)
{
    return uart8250_init(HARBOR_UART_BASE, HARBOR_UART_CLOCK,
                         HARBOR_UART_BAUD, 0, 1, 0);
}

static int ${name}_irqchip_init(bool cold_boot)
{
    int rc;

    if (cold_boot) {
        rc = plic_cold_irqchip_init(&plic);
        if (rc)
            return rc;
    }
    return plic_warm_irqchip_init(&plic,
                                  current_hartid() * 2,
                                  current_hartid() * 2 + 1);
}

static int ${name}_ipi_init(bool cold_boot)
{
    int rc;

    if (cold_boot) {
        rc = aclint_mswi_cold_init(&mswi);
        if (rc)
            return rc;
    }
    return aclint_mswi_warm_init();
}

static int ${name}_timer_init(bool cold_boot)
{
    int rc;

    if (cold_boot) {
        rc = aclint_mtimer_cold_init(&mtimer, NULL);
        if (rc)
            return rc;
    }
    return aclint_mtimer_warm_init();
}

const struct sbi_platform_operations platform_ops = {
    .early_init     = ${name}_early_init,
    .final_init     = ${name}_final_init,
    .console_init   = ${name}_console_init,
    .irqchip_init   = ${name}_irqchip_init,
    .ipi_init       = ${name}_ipi_init,
    .timer_init     = ${name}_timer_init,
};

const struct sbi_platform platform = {
    .opensbi_version   = OPENSBI_VERSION,
    .platform_version  = SBI_PLATFORM_VERSION(0, 1),
    .name              = "$name",
    .features          = SBI_PLATFORM_DEFAULT_FEATURES,
    .hart_count        = $hartCount,
    .hart_stack_size   = SBI_PLATFORM_DEFAULT_HART_STACK_SIZE,
    .heap_size         = SBI_PLATFORM_DEFAULT_HEAP_SIZE(${hartCount}),
    .platform_ops_addr = (unsigned long)&platform_ops,
};
''';
  }

  @override
  String toString() => 'OpenSbiPlatform($name)';

  @override
  String toPrettyString([
    HarborPrettyStringOptions options = const HarborPrettyStringOptions(),
  ]) {
    final p = options.prefix;
    final c = options.childPrefix;
    final buf = StringBuffer('${p}OpenSbiPlatform(\n');
    buf.writeln('${c}name: $name,');
    buf.writeln('${c}isa: ${isa.implementsString},');
    buf.writeln('${c}harts: $hartCount,');
    buf.writeln('${c}clint: 0x${clintBase.toRadixString(16)},');
    buf.writeln(
      '${c}plic: 0x${plicBase.toRadixString(16)} ($plicSources sources),',
    );
    buf.writeln('${c}uart: 0x${uartBase.toRadixString(16)},');
    buf.writeln(
      '${c}mem: 0x${memBase.toRadixString(16)} (${memSize ~/ (1024 * 1024)} MB),',
    );
    buf.write('$p)');
    return buf.toString();
  }
}
